name: Publish preview package
on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package-filename: ${{ steps.pack.outputs.filename }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Pack package
        id: pack
        run: |
          FILENAME=$(npm pack | tail -1)
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.pack.outputs.filename }}
          retention-days: 1
