name: Publish preview package
on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - run: bun install
      - run: bun run build
      - run: bunx pkg-pr-new publish
