name: Build dist/ and commit it to main branch

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "tsconfig.json"
      - ".github/workflows/publish-dist.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: rm -r dist || true
      - run: npm run build
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "📦 Update dist/ "
          add: "dist/*"
