name: Build dist/ and commit it to main branch

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "tsconfig.json"
      - ".github/workflows/publish-dist.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: rm -r dist || true
      - run: npm run build
      - name: Commit and push
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "📦 Update dist/ "
          add: "dist/*"
