name: Publish Typedoc to Github Pages
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run typedoc
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          destination_dir: docs
